### ISSUE TITLE
BrownianMotion sample_at losing the drift and scale

### ISSUE THREAD

**Issue by bozothegrey** [crflynn/stochastic#15]
Hello, I believe that _sample_brownian_motion_at is wrong as it calls it calls _sample_gaussian_noise_at and doesn't adjust for drift and scale. As a consequence, sample_at samples a Guassian Process. Please let me know if you would like me to work on it.

**Comment by crflynn** [comment]
Hi @bozothegrey. Thanks for pointing this out, you're right. If you're interested in fixing it go ahead. Otherwise I'll get to it when I can.

**Comment by MichaelHogervorst** [comment]
I've submitted a pull request to fix this issue.

**Comment by crflynn** [comment]
Closed by #23
