### ISSUE TITLE
New Continuous Process: Mixed Poisson 

### ISSUE THREAD

**Issue by Gabinou** [crflynn/stochastic#7]
This continuous stochastic process generates points distributed according to a rate generated from an arbitrary random distribution. I refer to the random distribution used to generate this rate is known as the information distribution.

The user would need to supply a random distribution in its parameters upon first call (numpy functions such as numpy.random.uniform). Then, a rate would be generated upon initialization. Upon each call of the sample method, a new random rate would be generated using the information distribution. 

Since this is a Poisson Process, the suggested MixedPoissonProcess class is very similar to the PoissonProcess class. Additionnal methods are setters and getters for the information process and parameters. Upon each call of the setters, a new rate is generated. Another additional method is the genrate method, which generates a new random rate using the previously supplied information distribution and parameters.

**Comment by crflynn** [comment]
I saw your PR for this process but I think it might be simpler to just subclass PoissonProcess and make use of the already existing code. Additionally, you would need to

* provide init args consisting of an RNG function, as well as args and kwargs for that function to ensure it is generalized enough for any rng package (random, numpy, scipy, etc.).
* make a call to rng_func(*args, **kwargs) to set the rate prior to sampling the poisson.

**Comment by Gabinou** [comment]
Following your comments and suggestions, I have implemented changes:

- MixedPoissonProcess now inherits from Poisson process. I have eliminated some amount of code repetition.
- Eliminated some other repetitions by way of the gen_rate() method.
- *rate_args and **rate_kwargs are implemented.
- New test fixtures for rate_kwargs. The tests seem to be in working order.
- Modified the continuous.rst to include the MixedPoissonProcess class. 

Still to be implemented is:
- Making sure the code fits style standards. I will work on that for the implementation of the appropriate features, mostly.


Is the pull request in a more acceptable state?
And thank you for your comments and help.

**Comment by crflynn** [comment]
This is ok but there are still a lot of issues that need to be addressed.

I think I might merge this into a separate dev branch and clean it up if you don't mind. I'm hoping that maybe you'll track the changes closely and if needed I can explain the reasoning for them. Is that ok?

**Comment by Gabinou** [comment]
This sounds marvelous. When it is up to scratch, I will use it as a template for my future pull requests.

Thank you very much!

**Comment by crflynn** [comment]
I requested some changes in the PR. Please address them. Thanks.

**Comment by Gabinou** [comment]
All changes were addressed. If this makes this feature acceptable, I will get to upgrading other features also.

**Comment by crflynn** [comment]
@Gabinou I have merged your PR #8  and made several changes that I think make the implementation a bit cleaner. You may refer to the commits in the [mixed](https://github.com/crflynn/stochastic/commits/mixed) branch for the changes. Thanks for contributing.
